### ISSUE TITLE
我用你的方法和接口写了个冒泡

### ISSUE THREAD

**Issue by shiroming** [xczh/ccoin#1]
https://git.coding.net/shiroming/CodingAutoTweet.git

**Comment by xczh** [comment]
Thank you for your concern and Tweet function has been included in modules/Tweet.py after v1.0.1. It's also avaliable on https://coding.net/u/xczh/p/coding_coins/git. Maybe, you forget to attach Apache License.

**Comment by shiroming** [comment]
嗯嗯  我看到里面的tweet了
版权已经修改
